

import javax.swing.JFrame;

/**
 *
 * @author Prakasz
 */
public class PilihKursi extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PilihKursi() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelMin1 = new javax.swing.JPanel();
        jLabelLogin1 = new javax.swing.JLabel();
        jLabelMin1 = new javax.swing.JLabel();
        jLabelMin2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setText(" ");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 40, -1));

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setText(" ");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 40, -1));

        jButton4.setBackground(new java.awt.Color(51, 204, 0));
        jButton4.setText(" ");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 40, -1));

        jButton5.setBackground(new java.awt.Color(51, 204, 0));
        jButton5.setText(" ");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 40, -1));

        jButton6.setBackground(new java.awt.Color(51, 204, 0));
        jButton6.setText(" ");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, -1));

        jButton7.setBackground(new java.awt.Color(51, 204, 0));
        jButton7.setText(" ");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 40, -1));

        jButton8.setBackground(new java.awt.Color(51, 204, 0));
        jButton8.setText(" ");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 40, -1));

        jButton9.setBackground(new java.awt.Color(51, 204, 0));
        jButton9.setText(" ");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 40, -1));

        jButton10.setBackground(new java.awt.Color(51, 204, 0));
        jButton10.setText(" ");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 40, -1));

        jButton11.setBackground(new java.awt.Color(51, 204, 0));
        jButton11.setText(" ");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 40, -1));

        jButton12.setBackground(new java.awt.Color(51, 204, 0));
        jButton12.setText(" ");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 40, -1));

        jButton13.setBackground(new java.awt.Color(51, 204, 0));
        jButton13.setText(" ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 40, -1));

        jButton14.setBackground(new java.awt.Color(51, 204, 0));
        jButton14.setText(" ");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 40, -1));

        jButton15.setBackground(new java.awt.Color(51, 204, 0));
        jButton15.setText(" ");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 40, -1));

        jButton16.setBackground(new java.awt.Color(51, 204, 0));
        jButton16.setText(" ");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 40, -1));

        jButton17.setBackground(new java.awt.Color(51, 204, 0));
        jButton17.setText(" ");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 40, -1));

        jButton18.setBackground(new java.awt.Color(51, 204, 0));
        jButton18.setText(" ");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 40, -1));

        jButton19.setBackground(new java.awt.Color(51, 204, 0));
        jButton19.setText(" ");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 40, -1));

        jButton20.setBackground(new java.awt.Color(51, 204, 0));
        jButton20.setText(" ");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 40, -1));

        jButton21.setBackground(new java.awt.Color(51, 204, 0));
        jButton21.setText(" ");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 40, -1));

        jButton22.setBackground(new java.awt.Color(51, 204, 0));
        jButton22.setText(" ");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 40, -1));

        jButton23.setBackground(new java.awt.Color(51, 204, 0));
        jButton23.setText(" ");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 40, -1));

        jButton24.setBackground(new java.awt.Color(51, 204, 0));
        jButton24.setText(" ");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 40, -1));

        jButton25.setBackground(new java.awt.Color(51, 204, 0));
        jButton25.setText(" ");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 40, -1));

        jButton26.setBackground(new java.awt.Color(51, 204, 0));
        jButton26.setText(" ");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 40, -1));

        jButton27.setBackground(new java.awt.Color(51, 204, 0));
        jButton27.setText(" ");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 40, -1));

        jButton28.setBackground(new java.awt.Color(51, 204, 0));
        jButton28.setText(" ");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 40, -1));

        jButton29.setBackground(new java.awt.Color(51, 204, 0));
        jButton29.setText(" ");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 40, -1));

        jButton30.setBackground(new java.awt.Color(51, 204, 0));
        jButton30.setText(" ");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 40, -1));

        jButton31.setBackground(new java.awt.Color(51, 204, 0));
        jButton31.setText(" ");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 40, -1));

        jButton33.setBackground(new java.awt.Color(51, 204, 0));
        jButton33.setText(" ");
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 40, -1));

        jButton34.setBackground(new java.awt.Color(51, 204, 0));
        jButton34.setText(" ");
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 40, -1));

        jButton36.setBackground(new java.awt.Color(51, 204, 0));
        jButton36.setText(" ");
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 40, -1));

        jButton37.setBackground(new java.awt.Color(51, 204, 0));
        jButton37.setText(" ");
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 40, -1));

        jButton38.setBackground(new java.awt.Color(51, 204, 0));
        jButton38.setText(" ");
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 40, -1));

        jButton39.setBackground(new java.awt.Color(51, 204, 0));
        jButton39.setText(" ");
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 40, -1));

        jButton40.setBackground(new java.awt.Color(51, 204, 0));
        jButton40.setText(" ");
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 40, -1));

        jButton41.setBackground(new java.awt.Color(51, 204, 0));
        jButton41.setText(" ");
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 40, -1));

        jButton42.setBackground(new java.awt.Color(51, 204, 0));
        jButton42.setText(" ");
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 40, -1));

        jButton44.setBackground(new java.awt.Color(51, 204, 0));
        jButton44.setText(" ");
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 40, -1));

        jButton45.setBackground(new java.awt.Color(51, 204, 0));
        jButton45.setText(" ");
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 40, -1));

        jButton47.setBackground(new java.awt.Color(51, 204, 0));
        jButton47.setText(" ");
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 40, -1));

        jButton48.setBackground(new java.awt.Color(51, 204, 0));
        jButton48.setText(" ");
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 40, -1));

        jButton50.setBackground(new java.awt.Color(51, 204, 0));
        jButton50.setText(" ");
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 40, -1));

        jButton51.setBackground(new java.awt.Color(51, 204, 0));
        jButton51.setText(" ");
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, -1));

        jButton52.setBackground(new java.awt.Color(51, 204, 0));
        jButton52.setText(" ");
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 40, -1));

        jButton53.setBackground(new java.awt.Color(51, 204, 0));
        jButton53.setText(" ");
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 40, -1));

        jButton54.setBackground(new java.awt.Color(51, 204, 0));
        jButton54.setText(" ");
        getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 40, -1));

        jButton55.setBackground(new java.awt.Color(51, 204, 0));
        jButton55.setText(" ");
        getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 40, -1));

        jButton56.setBackground(new java.awt.Color(51, 204, 0));
        jButton56.setText(" ");
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 40, -1));

        jButton57.setBackground(new java.awt.Color(51, 204, 0));
        jButton57.setText(" ");
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 40, -1));

        jButton58.setBackground(new java.awt.Color(51, 204, 0));
        jButton58.setText(" ");
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 40, -1));

        jButton60.setBackground(new java.awt.Color(51, 204, 0));
        jButton60.setText(" ");
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 40, -1));

        jButton61.setBackground(new java.awt.Color(51, 204, 0));
        jButton61.setText(" ");
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 40, -1));

        jButton62.setBackground(new java.awt.Color(51, 204, 0));
        jButton62.setText(" ");
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 40, -1));

        jButton63.setBackground(new java.awt.Color(51, 204, 0));
        jButton63.setText(" ");
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 40, -1));

        jButton64.setBackground(new java.awt.Color(51, 204, 0));
        jButton64.setText(" ");
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 40, -1));

        jButton65.setBackground(new java.awt.Color(51, 204, 0));
        jButton65.setText(" ");
        getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 40, -1));

        jButton66.setBackground(new java.awt.Color(51, 204, 0));
        jButton66.setText(" ");
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 40, -1));

        jButton67.setBackground(new java.awt.Color(51, 204, 0));
        jButton67.setText(" ");
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 40, -1));

        jButton68.setBackground(new java.awt.Color(51, 204, 0));
        jButton68.setText(" ");
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 40, -1));

        jButton69.setBackground(new java.awt.Color(51, 204, 0));
        jButton69.setText(" ");
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 40, -1));

        jButton70.setBackground(new java.awt.Color(51, 204, 0));
        jButton70.setText(" ");
        getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 40, -1));

        jButton71.setBackground(new java.awt.Color(51, 204, 0));
        jButton71.setText(" ");
        getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 40, -1));

        jButton72.setBackground(new java.awt.Color(51, 204, 0));
        jButton72.setText(" ");
        getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 40, -1));

        jButton73.setBackground(new java.awt.Color(51, 204, 0));
        jButton73.setText(" ");
        getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 40, -1));

        jButton74.setBackground(new java.awt.Color(51, 204, 0));
        jButton74.setText(" ");
        getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 40, -1));

        jButton75.setBackground(new java.awt.Color(51, 204, 0));
        jButton75.setText(" ");
        getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 40, -1));

        jButton76.setBackground(new java.awt.Color(51, 204, 0));
        jButton76.setText(" ");
        getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 40, -1));

        jButton77.setBackground(new java.awt.Color(51, 204, 0));
        jButton77.setText(" ");
        getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 40, -1));

        jButton78.setBackground(new java.awt.Color(51, 204, 0));
        jButton78.setText(" ");
        getContentPane().add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 40, -1));

        jButton79.setBackground(new java.awt.Color(51, 204, 0));
        jButton79.setText(" ");
        getContentPane().add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 40, -1));

        jButton80.setBackground(new java.awt.Color(51, 204, 0));
        jButton80.setText(" ");
        getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 40, -1));

        jButton81.setBackground(new java.awt.Color(51, 204, 0));
        jButton81.setText(" ");
        getContentPane().add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 40, -1));

        jButton82.setBackground(new java.awt.Color(51, 204, 0));
        jButton82.setText(" ");
        getContentPane().add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 40, -1));

        jButton83.setBackground(new java.awt.Color(51, 204, 0));
        jButton83.setText(" ");
        getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 40, -1));

        jButton84.setBackground(new java.awt.Color(51, 204, 0));
        jButton84.setText(" ");
        getContentPane().add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 40, -1));

        jButton85.setBackground(new java.awt.Color(51, 204, 0));
        jButton85.setText(" ");
        getContentPane().add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 40, -1));

        jButton86.setBackground(new java.awt.Color(51, 204, 0));
        jButton86.setText(" ");
        getContentPane().add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 40, -1));

        jButton87.setBackground(new java.awt.Color(51, 204, 0));
        jButton87.setText(" ");
        getContentPane().add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 40, -1));

        jButton88.setBackground(new java.awt.Color(51, 204, 0));
        jButton88.setText(" ");
        getContentPane().add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 40, -1));

        jButton89.setBackground(new java.awt.Color(51, 204, 0));
        jButton89.setText(" ");
        getContentPane().add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 40, -1));

        jButton90.setBackground(new java.awt.Color(51, 204, 0));
        jButton90.setText(" ");
        getContentPane().add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 40, -1));

        jButton91.setBackground(new java.awt.Color(51, 204, 0));
        jButton91.setText(" ");
        getContentPane().add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 40, -1));

        jButton92.setBackground(new java.awt.Color(51, 204, 0));
        jButton92.setText(" ");
        getContentPane().add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 40, -1));

        jButton93.setBackground(new java.awt.Color(51, 204, 0));
        jButton93.setText(" ");
        getContentPane().add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 40, -1));

        jButton94.setBackground(new java.awt.Color(51, 204, 0));
        jButton94.setText(" ");
        getContentPane().add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 40, -1));

        jButton95.setBackground(new java.awt.Color(51, 204, 0));
        jButton95.setText(" ");
        getContentPane().add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 40, -1));

        jButton96.setBackground(new java.awt.Color(51, 204, 0));
        jButton96.setText(" ");
        getContentPane().add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 40, -1));

        jButton97.setBackground(new java.awt.Color(51, 204, 0));
        jButton97.setText(" ");
        getContentPane().add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 40, -1));

        jButton98.setBackground(new java.awt.Color(51, 204, 0));
        jButton98.setText(" ");
        getContentPane().add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 40, -1));

        jButton99.setBackground(new java.awt.Color(51, 204, 0));
        jButton99.setText(" ");
        getContentPane().add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 40, -1));

        jButton100.setBackground(new java.awt.Color(51, 204, 0));
        jButton100.setText(" ");
        getContentPane().add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 40, -1));

        jButton101.setBackground(new java.awt.Color(51, 204, 0));
        jButton101.setText(" ");
        getContentPane().add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 40, -1));

        jLabel1.setText("J");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 20, -1));

        jLabel2.setText("A");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 20, -1));

        jLabel3.setText("B");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 20, -1));

        jLabel4.setText("C");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 20, -1));

        jLabel5.setText("D");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 20, -1));

        jLabel6.setText("E");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 20, -1));

        jLabel7.setText("F");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 20, -1));

        jLabel8.setText("G");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 20, -1));

        jLabel9.setText("H");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 20, -1));

        jLabel10.setText("I");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 20, -1));

        jLabel11.setText("10");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 40, -1));

        jLabel12.setText("1");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 20, -1));

        jLabel13.setText("2");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 40, -1));

        jLabel14.setText("3");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 40, -1));

        jLabel15.setText("4");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 40, -1));

        jLabel16.setText("5");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 40, -1));

        jLabel17.setText("6");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 40, -1));

        jLabel18.setText("7");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 40, -1));

        jPanelMin1.setBackground(new java.awt.Color(255, 153, 0));
        jPanelMin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelLogin1.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabelLogin1.setText("SILAHKAN PILIH KURSI YANG AKAN ANDA TONTON :");

        jLabelMin1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin1.setText("-");
        jLabelMin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMin1MouseClicked(evt);
            }
        });

        jLabelMin2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin2.setText("x");
        jLabelMin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMin2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMin1Layout = new javax.swing.GroupLayout(jPanelMin1);
        jPanelMin1.setLayout(jPanelMin1Layout);
        jPanelMin1Layout.setHorizontalGroup(
            jPanelMin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMin1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelMin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMin2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMin1Layout.setVerticalGroup(
            jPanelMin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMin1Layout.createSequentialGroup()
                .addGroup(jPanelMin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin1)
                    .addComponent(jLabelLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMin2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        jLabel19.setText("8");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 10, -1));

        jLabel20.setText("9");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 30, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("PINTU MASUK");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("LAYAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void jLabelMin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMin1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMin1MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jLabelMin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMin2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelMin2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihKursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihKursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihKursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihKursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihKursi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogin1;
    private javax.swing.JLabel jLabelMin1;
    private javax.swing.JLabel jLabelMin2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMin1;
    // End of variables declaration//GEN-END:variables
}
