
import static java.lang.Compiler.command;


public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
        MilihFilm film = new MilihFilm();
        TipeFilm tipe = new TipeFilm();
        JamTayang jam = new JamTayang();
        JDL.setText(film.judulFilm);
        hari.setText(jam.hari);
        waktu.setText(jam.jam);
        hargat.setText("Rp. "+ Integer.toString(jam.harga));
        jLabel3.setText(jam.bangku);
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Judul = new javax.swing.JLabel();
        jLabel_judul = new javax.swing.JLabel();
        jLabel_tanggal = new javax.swing.JLabel();
        jLabel_waktu = new javax.swing.JLabel();
        jLabel_row = new javax.swing.JLabel();
        jLabel_harga = new javax.swing.JLabel();
        hari = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hargat = new javax.swing.JLabel();
        JDL = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Judul.setFont(new java.awt.Font("OCR A Extended", 3, 20)); // NOI18N
        Judul.setText("CGV BLITZMEGAPLEX");
        getContentPane().add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 240, 20));

        jLabel_judul.setText("Judul     :");
        getContentPane().add(jLabel_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel_tanggal.setText("Hari       :");
        getContentPane().add(jLabel_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 19));

        jLabel_waktu.setText("Waktu   :");
        getContentPane().add(jLabel_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, -1));

        jLabel_row.setText("Seat      :");
        getContentPane().add(jLabel_row, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, -1));

        jLabel_harga.setText("Harga   :");
        getContentPane().add(jLabel_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        hari.setText("Hari");
        getContentPane().add(hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, 30));

        waktu.setText("jLabel1");
        getContentPane().add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 30));

        jLabel3.setText("A10");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 100, 30));

        hargat.setText("harga");
        getContentPane().add(hargat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 110, 30));

        JDL.setText("judul");
        JDL.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                JDLInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(JDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 200, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/step_06_aging_the_ticket_01.jpg"))); // NOI18N
        background.setText("Time / Date Order");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JDLInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JDLInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JDLInputMethodTextChanged


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JDL;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel background;
    private javax.swing.JLabel hargat;
    private javax.swing.JLabel hari;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_harga;
    private javax.swing.JLabel jLabel_judul;
    private javax.swing.JLabel jLabel_row;
    private javax.swing.JLabel jLabel_tanggal;
    private javax.swing.JLabel jLabel_waktu;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
